//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// --------------------- Global Variables ---------------------

struct _IO_FILE * g1 = NULL; // 0x804a02c

// ------------------------ Functions -------------------------

// Address range: 0x80484ed - 0x80485cf
int main(int argc, char ** argv) {
    printf("enter a number 1:");
    int32_t str;
    fgets((char *)&str, 50, g1);
    printf("enter a number 2:");
    int32_t str2;
    fgets((char *)&str2, 50, g1);
    int32_t str_as_i = atoi((char *)&str); // 0x8048561
    int32_t str_as_i2 = atoi((char *)&str2); // 0x8048571
    printf("%d/%d = %d\n", str_as_i, str_as_i2, (int32_t)((0x100000000 * (int64_t)(str_as_i >> 31) | (int64_t)str_as_i) / (int64_t)str_as_i2));
    if (*(int32_t *)20 != *(int32_t *)20) {
        // 0x80485c0
        __stack_chk_fail();
        // branch -> 0x80485c5
    }
    // 0x80485c5
    return 0;
}

// --------------- Dynamically Linked Functions ---------------

// void __stack_chk_fail(void);
// int atoi(const char * nptr);
// char * fgets(char * restrict s, int n, FILE * restrict stream);
// int printf(const char * restrict format, ...);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (4.8.2)
// Detected functions: 1
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-06-02 12:37:51
